name: Build and Publish MCP Server

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'  # Trigger on version tags (v0.41.0, v1.0.0, etc.)
    paths:
      - 'gns3_mcp/**'
      - 'mcp-server/manifest.json'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/build-mcpb.yml'

permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies for cairosvg
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev

      - name: Create lib directory
        run: |
          mkdir -p mcp-server/lib

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=mcp-server/lib \
            fastmcp>=2.13.0.2 \
            httpx>=0.28.1 \
            telnetlib3>=2.0.8 \
            pydantic>=2.12.3 \
            python-dotenv>=1.2.1 \
            cairosvg>=2.8.2 \
            docker>=7.1.0 \
            tabulate>=0.9.0 \
            --no-warn-script-location

          # Install build tools for PyPI
          pip install build twine

      - name: Verify dependencies installed
        run: |
          ls -la mcp-server/lib
          echo "Installed packages:"
          ls mcp-server/lib | head -20

      - name: Build MCP binary
        run: |
          cd mcp-server
          npx @anthropic-ai/mcpb pack

      - name: Verify build output
        run: |
          if [ ! -f mcp-server/mcp-server.mcpb ]; then
            echo "Error: mcp-server.mcpb was not created"
            exit 1
          fi
          ls -lh mcp-server/mcp-server.mcpb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server-binary
          path: mcp-server/mcp-server.mcpb
          retention-days: 30

      - name: Extract version and check for tag
        id: version
        run: |
          VERSION=$(python -c "import json; print(json.load(open('mcp-server/manifest.json'))['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"
          
          # Check if current commit has a version tag
          if git describe --exact-match --tags HEAD 2>/dev/null | grep -q "^v"; then
            echo "is_tagged=true" >> $GITHUB_OUTPUT
            echo "This commit is tagged for release"
          else
            echo "is_tagged=false" >> $GITHUB_OUTPUT
            echo "This commit is not tagged"
          fi

      - name: Build PyPI distributions
        if: steps.version.outputs.is_tagged == 'true'
        run: |
          python -m build
          ls -lh dist/

      - name: Publish to PyPI
        if: steps.version.outputs.is_tagged == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload dist/*

      - name: Create Release
        if: steps.version.outputs.is_tagged == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mcp-server/mcp-server.mcpb
            dist/*.whl
            dist/*.tar.gz
          tag_name: v${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## GNS3 MCP Server v${{ steps.version.outputs.version }}

            ### Installation

            **Via pip (Recommended):**
            ```bash
            pip install gns3-mcp
            ```

            **Via Claude Desktop:**
            Download `mcp-server.mcpb` and install via Claude Desktop settings.

            ### Changes
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/master/CHANGELOG.md) for details.
          draft: false
          prerelease: false
