name: Build MCP Server Binary

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches:
      - main
    paths:
      - 'mcp-server/**'
      - 'requirements.txt'
      - '.github/workflows/build-mcpb.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install system dependencies for cairosvg
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libpango1.0-dev

      - name: Create lib directory
        run: |
          mkdir -p mcp-server/lib

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=mcp-server/lib \
            fastmcp>=2.13.0.2 \
            httpx>=0.28.1 \
            telnetlib3>=2.0.8 \
            pydantic>=2.12.3 \
            python-dotenv>=1.2.1 \
            cairosvg>=2.8.2 \
            docker>=7.1.0 \
            tabulate>=0.9.0 \
            --no-warn-script-location

      - name: Verify dependencies installed
        run: |
          ls -la mcp-server/lib
          echo "Installed packages:"
          ls mcp-server/lib | head -20

      - name: Build MCP binary
        run: |
          cd mcp-server
          npx @anthropic-ai/mcpb pack

      - name: Verify build output
        run: |
          if [ ! -f mcp-server/mcp-server.mcpb ]; then
            echo "Error: mcp-server.mcpb was not created"
            exit 1
          fi
          ls -lh mcp-server/mcp-server.mcpb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mcp-server-binary
          path: mcp-server/mcp-server.mcpb
          retention-days: 30
